### ISSUE TITLE
Not working on 3.10 anymore

### ISSUE THREAD

**Issue by rickinbsb** [ozonos/atom-launcher#10]
since the latest editions, atom-launcher doesn`t work on 3.10 anymore.

also, the 3.12 especific branch is now dead?

**Comment by me4oslav** [comment]
Do we care about 3.10 anymore?

**Comment by rickinbsb** [comment]
I believe there are no reasons anymore

**Comment by rickinbsb** [comment]
unless you pretend to support people still using ubuntu-gnome 14.04 or older

**Comment by me4oslav** [comment]
Well, 14.04 is an LTS, but 3.10 is such an old version of Gnome. APIs were different in it and stuff, so backporting the extension to it may not be worth it.

**Comment by rickinbsb** [comment]
Is it too lazy to just keep a branch with an older version of the extension?

**Comment by me4oslav** [comment]
Could work. Do we have such branch?

**Comment by rickinbsb** [comment]
nope, the last commit known to work on 12.10 is 80236e42b9325e851aba11860fbeea841057001b

**Comment by me4oslav** [comment]
Hmm. Can somebody do that a branch?
