### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Foggalong** [ozonos/atom-launcher#11]
Runs fine without errrors but doesn't result in the laucnher extension being installed.

**Comment by me4oslav** [comment]
Wat? :o

**Comment by cldx** [comment]
This is 3 months old, is it even relevant?

**Comment by Foggalong** [comment]
No idea if this is still the case. Can't even remember if it was a packaging issue or just general code :P

**Comment by Foggalong** [comment]
Paolo's closed it so assuming it's fixed
