### ISSUE TITLE
Atom dash doesn't work in GNOME 3.12

### ISSUE THREAD

**Issue by satya164** [ozonos/atom-launcher#6]
I cannot even enable it due to error in loading. I guess it's some API incompatibility.

Here is a screenshot showing the error message in looking glass,

![screenshot from 2014-04-13 22 53 46](https://cloud.githubusercontent.com/assets/1174278/2690155/c78dd2d0-c331-11e3-8af2-a963a66ca3ea.png)

**Comment by me4oslav** [comment]
It works now.
